---
- hosts: localhost
  become: yes

  tasks:
    - name: Install deluge
      apt: pkg=deluge state=present

    - name: Install vim
      apt: pkg=vim state=present

    - name: Install x2go client
      apt: pkg=x2goclient state=present

    - name: Install tmux
      apt: pkg=tmux state=present

