---
- hosts: local
  become: yes

  tasks:
  - name: Update package list
    apt: update_cache=yes

  - name: Ensure that system daemon is installed
    apt: pkg=systemd state=present

  - name: Add deluge system user
    user:
      name: deluge
      comment: Deluge Service
      system: yes
      password_lock: no
      home: /var/lib/deluge

  - name: Ensure that deluge daemon is installed
    apt: pkg=deluged state=present

  - name: Ensure that deluge console is installed
    apt: pkg=deluge-console state=present

  - name: Ensure that deluge web UI is installed
    apt: pkg=deluge-web state=present

  - name: Config the deluge daemon service
    template:
      src: deluged.service
      dest: /etc/systemd/system/deluge_daemon.service

  - name: Start deluge daemon to create default config (if none present)
    service: name=deluge_daemon state=started

  - name: Wait a few seconds (ensure deluged has time to do it's job)
    pause: seconds=10

  - name: Stop deluge daemon (we will modify some config files)
    service: name=deluge_daemon state=stopped

  - name: Add new user to deluge daemon
    lineinfile:
      dest: /var/lib/deluge/.config/deluge/auth
      line: 'deluge:deluge:10'
      state: present

  - name: Allow remote connection to deluge daemon
    lineinfile:
      dest: /var/lib/deluge/.config/deluge/core.conf
      regexp: "\"allow_remote\": (false|true),"
      line: "  \"allow_remote\": true, "
      state: present
  
  - name: Start deluge daemon at boot-up
    service: name=deluge_daemon enabled=yes state=started

  - name: Config the deluge web UI service
    template:
      src: deluge-web.service
      dest: /etc/systemd/system/deluge-web.service

  - name: Start deluge web UI at boot-up
    service: name=deluge-web enabled=yes state=started
