---
- hosts: localhost

  tasks:
    - name: Install vim
      apt: pkg=vim state=present
      become: yes

    - name: Create symbolic link for .vimrc
      file:
        src: "~/dotfiles/.vimrc"
        dest: "~/.vimrc"
        state: link

    - name: Install minpac (vim package manager)
      git:
        repo: "https://github.com/k-takata/minpac.git"
        dest: ~/.vim/pack/minpac/opt/minpac

    - name: Install tmux
      apt: pkg=tmux state=present
      become: yes

    - name: Create symbolic link for .tmux.conf
      file:
        src: "~/dotfiles/.tmux.conf"
        dest: "~/.tmux.conf"
        state: link

    - name: Install deluge
      apt: pkg=deluge state=present
      become: yes

    - name: Install x2go client
      apt: pkg=x2goclient state=present
      become: yes

    - name: Set regular clean-up of the Downloads directory
      cron:
        name: "Remove old files from Downloads"
        special_time: "hourly"
        job: "~/dotfiles/scripts/remove_old_files_from_downloads.sh"
        user: "alex"

